spring:
  application:
    name: adventure-book-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: ${PORT:8081}
app:
  books:
    seed-location: ${SEED_LOCATION:classpath:data/*.json}